version: "3.5"
services:
  web-server:
    image: tt_app:client3
    container_name: tt_client
    ports:
      - 3000:80
    restart: always
    depends_on:
      - node-server

  node-server:
    image: tt_app:server
    container_name: tt_server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db

  db:
    container_name: postgresDB
    image: postgres
    restart: always
    ports:
      - 5005:5432
    volumes:
      - db-data:/etc/data
    environment:
      POSTGRES_PASSWORD: 1111
      PGDATA: /etc/data

volumes:
  db-data:
