FROM node:20.11.0

WORKDIR /usr/src/app

COPY package*.json ./

WORKDIR /usr/src/app/server
COPY server/package*.json ./
RUN npm install --omit=dev

WORKDIR /usr/src/app
COPY server/ ./server/

EXPOSE 5000

CMD ["npm", "run", "start"]
