FROM node:20.11.0

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

WORKDIR /usr/src/app/client
COPY client/package*.json ./
RUN npm install

WORKDIR /usr/src/app/server
COPY server/package*.json ./
RUN npm install

WORKDIR /usr/src/app
COPY . .

EXPOSE 5000
EXPOSE 3000

CMD [ "npm", "run", "dev" ]
